### ISSUE TITLE
Error sending audio to hume

### ISSUE THREAD

**Issue by kashifnazeer62** [HumeAI/hume-typescript-sdk#244]
I am working with hume sdk in my react native expo application
here is my function that i am using to send audio to hume 

facing following error

` (NOBRIDGE) ERROR  Error sending audio to Hume: [Error: type: [Variant 0] Expected "audio_input". Received "user_input".; [Variant 0] Missing required key "data"; type: [Variant 1] Expected "session_settings". Received "user_input".; text: [Variant 2] Expected string. Received object.; type: [Variant 3] Expected "assistant_input". Received "user_input".; text: [Variant 3] Expected string. Received object.; type: [Variant 4] Expected "tool_response". Received "user_input".; [Variant 4] Missing required key "toolCallId"; [Variant 4] Missing required key "content"; type: [Variant 5] Expected "tool_error". Received "user_input".; [Variant 5] Missing required key "toolCallId"; [Variant 5] Missing required key "error"; type: [Variant 6] Expected "pause_assistant_message". Received "user_input".; type: [Variant 7] Expected "resume_assistant_message". Received "user_input".]`

```
const startRecording = async () => {
        try {
            console.log("Requesting microphone permissions...");
            const { status } = await Audio.requestPermissionsAsync();

            if (status !== 'granted') {
                console.error("Permission not granted for audio recording.");
                alert("Microphone permission is required to start recording.");
                return;
            }

            await Audio.setAudioModeAsync({
                allowsRecordingIOS: true,
                playsInSilentModeIOS: true,
            });

            console.log("Starting recording...");
            const recording = new Audio.Recording();
            await recording.prepareToRecordAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY);

            await recording.startAsync();
            recordingRef.current = recording;
            setIsRecording(true);
        } catch (error) {
            console.error("Error starting recording:", error);
            setIsRecording(false);
        }
    };

    const stopRecording = async () => {
        try {
            console.log("Stopping recording...");
            if (recordingRef.current) {
                await recordingRef.current.stopAndUnloadAsync();
                const uri = recordingRef.current.getURI();
                if (!uri) {
                    console.error("Recording URI is null.");
                    return;
                }
                console.log("Recording saved at:", uri);

                // Play the recorded message first
                await playRecordedMessage(uri);

                const audioBase64 = await FileSystem.readAsStringAsync(uri, {
                    encoding: FileSystem.EncodingType.Base64,
                });

                await sendAudioToHume(audioBase64);

                recordingRef.current = null;
            }
            setIsRecording(false);
        } catch (error) {
            console.error("Error stopping recording:", error);
        }
    };

const sendAudioToHume = async (audioBase64: string) => {
        try {
            if (!socket) {
                console.error("Socket is not connected.");
                return;
            }

            console.log("Sending audio to Hume...");
            // Add a temporary message to show that audio is being sent
            setMessages(prev => [...prev, { role: "User", content: "🎤 Voice message sent" }]);

            // Format the audio data according to Hume's requirements
            const audioPayload = {
                type: "audio_input",
                data: {
                    audio: {
                        data: audioBase64,
                        format: "audio/m4a"
                    }
                }
            };

            // Send the properly formatted audio data
            socket.sendUserInput(audioPayload);
            console.log("Audio sent successfully.");
        } catch (error) {
            console.error("Error sending audio to Hume:", error);
            setMessages(prev => [...prev, {
                role: "System",
                content: `Error sending voice message: ${error}`
            }]);
        }
    };
```

here is my front end component
    
```
{inputText.trim() ? (
                            <Pressable style={styles.voiceButton} onPress={sendMessage}>
                                <FontAwesome name="paper-plane" size={24} color={CustomColors.white} />
                            </Pressable>
                        ) : (
                            <Pressable style={styles.voiceButton} onPressIn={startRecording} onPressOut={stopRecording}>
                                <FontAwesome name="microphone" size={24} color={CustomColors.white} />
                            </Pressable>
                        )}
```

**Comment by twitchard** [comment]
Two other things:
* Make sure to check out the [React Native EVI example](https://github.com/HumeAI/hume-api-examples/tree/main/evi-react-native-example) if you haven't seen it.
* Based on your code, it looks to me like you are using the [`expo-audio`](https://docs.expo.dev/versions/latest/sdk/audio/) library for audio recording. Something you might run into: EVI can work poorly if you don't enable echo cancellation on the stream e.g. on web you would do
```javascript
    navigator.mediaDevices.getUserMedia({
        audio: {
            echoCancellation: true,
    ...
```

on iOS you [would do](https://github.com/HumeAI/hume-api-examples/blob/c0eeb334a2d1d8a812d52308c8c5ba4f9ab9ef2d/evi-react-native-example/modules/audio/ios/Microphone.swift#L23-L39)
```swift
            try self.inputNode.setVoiceProcessingEnabled(true)
            try outputNode.setVoiceProcessingEnabled(true)
```

When I was researching the expo-audio library I didn't see a way to enable echo cancellation -- so that's a problem you might run into. Without echo cancellation, unless you are wearing headphones, EVI will hear and respond to its own speech and this can lead to a bad experience.

Anyway, if you find a way to get this to work with expo-audio I would be curious to hear how. Otherwise, I think you will have to take an approach more similar to the [React Native EVI example](https://github.com/HumeAI/hume-api-examples/tree/main/evi-react-native-example) where you maintain your own expo module for handling audio.
